### ISSUE TITLE
Google Test is fetched two times

### ISSUE THREAD

**Issue by riemann89** [clearmatics/zeth#10]
Google test dependency is added two times into the project. At the repo level, there is no problem since we have just two references, so no big deal. But when we run `submodule update init --recursive` we download it two times. So it would be nice to remove one of the two occurrences (the one in our dependency folder `depends/googletest`, leaving the one in the libsnark-fork folder in order to diverge as less as possible from the main repo).

**Comment by AntoineRondelet** [comment]
Closing this issue as the corresponding PR has been merged
