### ISSUE TITLE
h_sig independant to vk

### ISSUE THREAD

**Issue by rrtoledo** [clearmatics/zeth#120]
In the non-malleability upgrade, we introduced a few variables including h_sig. h_sig is used to compute the message authentication tags (h_i) and the new notes identifiers (h_i). h_sig is computed as the hash of the signature verification key (vk), some randomness (randomSeed) and the old notes nullifiers ({nf}_old).

The vulnerability is that we do not check anywhere that h_sig is correctly computed, and even provide it to the contract (see "verifyTransaction in [Zerocash full paper](http://zerocash-project.org/media/pdf/zerocash-extended-20140518.pdf) Figure 2 p21). An adversary could thus take the primary inputs (including h_sig) and the proof and create a new transaction with them (by faking the ciphertexts and creating a new verification key/signature).

To correct the vulnerability we need to force the contract to check the correctness of h_sig. We could,
- remove h_sig from the "inputs" variable and have the contract recompute them. This would be cheaper in term of variable but we would need extra computation to reassemble the primary inputs.
- check that h_sig = Hash( randomSeed,  vk, {nf_{old}}. We already reassemble the {nf_{old}} so this solution should cost us a hash.

**Comment by AntoineRondelet** [comment]
Related to https://github.com/clearmatics/zeth/pull/43/files

**Comment by AntoineRondelet** [comment]
Closing this issue since it has been addressed and merged
