### ISSUE TITLE
Optimise contract primary inputs assembly

### ISSUE THREAD

**Issue by rrtoledo** [clearmatics/zeth#133]
For the assembly of the $nf$ in `    function check_mkroot_nullifiers_hsig_append_nullifiers_state(
`, it should be more efficient to have a second counter actually than recomputing the index (as we would have a C_variable_declaration + jsinC_addition instead of jsin(C_addition + C_division) and C_var_declaration < C_division ).
something like:

```
uint nf_count;
for(uint i = 1; i < 1 + 2*jsIn; i += 2) {  
    digest_inputs[0] = primary_inputs[i];  
    digest_inputs[1] = primary_inputs[i+1];  
    bytes32 current_nullifier = Bytes.sha256_digest_from_field_elements(digest_inputs);  
    nfs[nf_count] = Bytes.sha256_digest_from_field_elements(digest_inputs);  
    nf_count = nf_count + 1;  
}
```

**Comment by dtebbs** [comment]
Handled as part of #138 

(For reference, the saving here was approx ~600 gas.  Removing the `memory` in local variables and arguments gives a much greater gas saving.)

**Comment by AntoineRondelet** [comment]
Closing this issue since the related PR has been merged (please re-open if necessary @dtebbs @rrtoledo)
