### ISSUE TITLE
Make digest packing bit order match the EVM

### ISSUE THREAD

**Issue by dtebbs** [clearmatics/zeth#142]
Currently, when digests are packed into multiple field elements, the bits are ordered so that bit0 of the digest has lowest order, and bit255 has highest.

For big-endian machines, the full set of 256 bits must be reversed.  For little-endian machines, the bits in each byte must be reveresed.  In particular, this wastes gas in the mixer contract (which hits the big-endian case above).

**Comment by AntoineRondelet** [comment]
Closing this issue since the associated PR has been merged
