### ISSUE TITLE
Contract compilation error with solc-v0.6.1

### ISSUE THREAD

**Issue by riemann89** [clearmatics/zeth#146]
Currently if a user clones and executes Zeth from scratch will incur in a compilation error caused by `py-solcx-v0.1.1` compiling with `solc-v0.6.1` and deprecated flags. This happens if no compiler is available and, by default, the latest version is downloaded. More recent releases of `py-solcx` avoid this problems since they check the compiler version and filter unsupported options.  Updating `py-solcx` would solve this problem but it will introduce two different issues:

-  `solc-v.0.6.1` cannot be used in any case with our contracts since we have to stick to versions 0.5.x.

-  compiler installation folder used by `py-solcx` has changed and now `$HOME/.solcx` is used. So we are not able anymore to take everything into the virtual environment if we install the compiler by using the wrapper.

At the moment, a possible  solution is to update `py-solcx` and then force the installation of the right version of the compiler, either before the `make setup` of the python client or by adding the related installation command in the tests i.e. `install_solc('v0.5.x')`. The compiler has to be installed into the `$HOME/.solcx` folder since it's the place where `py-solcx` looks for. 
To keep everything into the virtual environment we should propose to the `py-solcx` mainteiners to support a custom installation folder for the compiler.

**Comment by dtebbs** [comment]
> solc-v.0.6.1 cannot be used in any case with our contracts since we have to stick to versions 0.5.x.

Just out of interest, where does this requirement come from?
Is it just a matter of updating the contract code, or is there some other restriction?  (no suggesting a specific solution, just wondering).

Would it be failry straightforward to replicate the "Install solc manually" steps for the version we require somewhere during `make setup` and keep the `py-solcx` version as it is until they support compiler locations other than `$HOME/.solcx`?

**Comment by riemann89** [comment]
> Just out of interest, where does this requirement come from?

This follow from the fact that in the contract is used `pragma ^0.5.0` so only successive version of solidity compiler up to 0.6.0 (excluded) can be used. See [here](https://solidity.readthedocs.io/en/v0.6.1/layout-of-source-files.html) Version Pragma. Btw I haven't investigated about the possibility to increase pragma version in our contracts.

> Would it be failry straightforward to replicate the "Install solc manually" steps for the version we require somewhere during make setup and keep the py-solcx version as it is until they support compiler locations other than $HOME/.solcx?

Yes this is a valid option, but it would be better to have a newer version soon I guess.

**Comment by dtebbs** [comment]
> This follow from the fact that in the contract is used pragma ^0.5.0 so only successive version of solidity compiler up to 0.6.0 (excluded) can be used. See here Version Pragma. Btw I haven't investigated about the possibility to increase pragma version in our contracts.

I see.  I was just wondering if there is something prevening us from using the newer compiler.

Not that I'm suggesting we do that immediately - I think it's important that we insulate the code from sudden releases like this so we can move to the newer compiler on our own schedule (even if that means keeping an older version of the `py-solcx` wrapper for now).  If everything can break because someone releases something new, outside of our control, then I think that's a problem.

**Comment by dtebbs** [comment]
I'm not sure I understood the original situation ... will the newer versions of `py-solcx` allow us to specify the solc version we want, and install this version for us in `$HOME/.solcx` *alongside* any existing versions?  If so, I think it does make sense to upgrade.

It may install solc outside of the env, but I think that's an acceptable price to pay in order to insulate the code from releases outside of our control.

**Comment by riemann89** [comment]
>  I'm not sure I understood the original situation ... will the newer versions of py-solcx allow us to specify the solc version we want, and install this version for us in $HOME/.solcx alongside any existing versions? If so, I think it does make sense to upgrade.

The choice of the version to install was already available before, what it is change now is just the folder where the compiler is installed. Unfortunately there is no way to change the installation folder. So we could still use the old version to take the compiler inside the environment, but as you said it is acceptable to have a newer version of the wrapper and have the compiler outside.

**Comment by dtebbs** [comment]
> The choice of the version to install was already available before, what it is change now is just the folder where the compiler is installed. Unfortunately there is no way to change the installation folder. So we could still use the old version to take the compiler inside the environment, but as you said it is acceptable to have a newer version of the wrapper and have the compiler outside.

I see.  In that case, I misunderstood.  If we can control the version that gets installed then no problem.

**Comment by AntoineRondelet** [comment]
Closing this issue since the corresponding PR has been merged
