### ISSUE TITLE
Benchmarks for realistic Merkle tree depths

### ISSUE THREAD

**Issue by dtebbs** [clearmatics/zeth#152]
Benchmark proof gen and contract gas costs with larger commitment tree depths.
As well as giving an estimate for costs in more realistic situations, this may also reveal issues in the code (misuse of constants, handling of larger data, etc)

**Comment by dtebbs** [comment]
(after discussion with @rrtoledo )

Step 1 can be to measure the cost of various depth on a regular laptop to understand scaling.
Interesting Step 2 coudl be to also measure how proving times change with the number of cores available.

Based on this we can estimate realistic proof times on various hardware profiles.

**Comment by AntoineRondelet** [comment]
Note that as discussed off-line, Merkle Shrubs (https://github.com/matter-labs/MerkleShrubs) can be of interest here and may help improving perfs. To investigate.

**Comment by dtebbs** [comment]
Also worth thinking about the input packing technique as another way to cut gas costs (at the expense of circuit complexity).
https://eprint.iacr.org/2020/156.pdf

**Comment by AntoineRondelet** [comment]
Closing this issue since the associated PR (https://github.com/clearmatics/zeth/pull/154) has been merged
