### ISSUE TITLE
Parametrize circuits

### ISSUE THREAD

**Issue by rrtoledo** [clearmatics/zeth#153]
The joinsplit circuit is parametrize for arbitrary number of input and output notes but not for digest length and field capacity (see packing and unpacking variable are set to 1).

This issue is primarily to parametrize according to digest length and field capacity. The assignee should also parametrize the length of the primary and auxiliary inputs (rho, phi, hsig) by creating constants in file "zeth.h".

**Comment by AntoineRondelet** [comment]
We need to be consistent with the constants, and use the same units. Some constants in the solidity code are expressed in bits, and same constants are expressed in bytes in the cpp code. We should either add the unit as part of the constant name, or use the same units everywhere to raise ambiguity.

**Comment by AntoineRondelet** [comment]
Seems like we would need to use the `nb_field_residual` const in several places in the joinsplit.tcc file (here https://github.com/clearmatics/zeth/blob/develop/src/circuits/joinsplit.tcc#L48 for eg, we have `+1` at the end, which trully would need to be `+ nb_field_residual`).

**Comment by rrtoledo** [comment]
I will have a look at it @AntoineRondelet . Just note, that we use `+1` sometimes to define a `pb_variable_array` that is fillled with `nb_field_residual` elements.

**Comment by rrtoledo** [comment]
I would keep the `+1` as using `nb_field_residual` packers (as well as packed and unpacked variables) would make things more complex.

Indeed if we want to have one packer per f.e. of the residual bits we would have to manually compute when to stop adding bits (from nf, cm, vin, vout, ...). The simplest way to do that would be to have a unique counter and another pb_variable_array where we would already have concatenated all the residual bits. All in all, we would add `nb_field_residual -1` packer gadgets, and `2 * nb_field_residual` variables.

**Comment by AntoineRondelet** [comment]
Yeah I see, you call the `packing` subcircuit inside a "for" loop and you change the wires coming "in" and going "out" according to the iteration, instead of "unrolling the loop". That works.

**Comment by AntoineRondelet** [comment]
Closing this issue since the corresponding PR has been merged.
