### ISSUE TITLE
Hard-coded depth conflicts with parameters

### ISSUE THREAD

**Issue by dtebbs** [clearmatics/zeth#156]
In the circuit generation code, some places appear to support different Merkle tree depths whereas other parts of the code use the ZETH_MERKLE_TREE_DEPTH constant. Some unit test code attempts to use ZETH_MERKLE_TREE_DEPTH_TEST, which causes many runtime errors if this value is not the same as ZETH_MERKLE_TREE_DEPTH.

Ideally, tree depth would be a parameter everywhere (template parameter so that the compiler can detect places where sizes may not be as expected).

(Tangentially related to #153 )

**Comment by AntoineRondelet** [comment]
Closing this issue as it has been addressed in #154 which is merged now
