### ISSUE TITLE
Using Blake2s Hash function to generate the commitment

### ISSUE THREAD

**Issue by rrtoledo** [clearmatics/zeth#158]
If we were to use Blake2s hash function instead of recursive calls to Blake2s compression function, we could save close a whole compression worth of constraints (~22k) per commitment.

Right now, the compression function is defined as y = comp(m_0, m_1). The `initial state` (you can see it as an IV dependent on the block and digest lengths) is hard-coded as we assume that the messages length is constant.
To compute cm, we do so far: cm = comp( comp(r_trap, comp(apk, rho)), v) (I simplified the expression by not denoting the padding and truncation).

If we use the hash function, the state becomes a chaining value, a variable. Let h be this new variable, let's redefine the compression function as y = comp(h, m_0,m_1).
Hashing to obtain cm we would have:
h_1 = comp(h_0, apk, rho)
h_2 = comp(h_1, rtrap, v)
As you can see, we save one call of a compression function. Making the state h a variable does not directly add any constraint. We would still assume that the size of the input is fixed (in order to save some constraints). This function would thus be a hash on two set of inputs of size 2x256 each.

There would be a design choice to either implement a separate hash circuit calling the compress circuit several time and setting the chaining values or having the chaining values being set directly in the commitment and PRF gadgets.
The first choice would be cleaner, while the second would let us revert to using the compression function only more easily.

**Comment by AntoineRondelet** [comment]
Closing this issue since the corresponding PR has been merged
