### ISSUE TITLE
Possible attack to steal `vout`

### ISSUE THREAD

**Issue by dtebbs** [clearmatics/zeth#160]
The attack below seems to be a vulnerability:

User U broadcasts a transaction to which calls \mix to withdrawn funds from the mixer. A malicious Ethereum node A notices the transaction in the mempool, resigns and rebroadcasts it from his own Ethereum address (with a higher gas price).
If the resigned tx is executed first, A will receive the \mix output \vout.

If the above is a genuine vulnerability, the \mix parameters must be tied to the sender (via $\hsig$?) and the contract code must check this against `eth.sender`.

**Comment by rrtoledo** [comment]
Good find.
I missed that in the non malleability update. We need the client to also sign alongside the proof the recipient address with the OT signature scheme (it is denoted by `info` in ZeroCash).

**Comment by dtebbs** [comment]
Ah, yes. Easier to have the client sign the recipient address rather than put it in `hsig`.

**Comment by dtebbs** [comment]
After a quick discussion with @rtoledo, we proposed the following simple change to address this:
- user adds his Ethereum address to the data to be signed
- mixer contract uses `eth.sender` to reconstruct the data to be signed (rejecting the tx if the signature check fails, as now)

**Comment by AntoineRondelet** [comment]
Thanks guys. I close this issue now as the corresponding PR has been merged.
