### ISSUE TITLE
Update documentation to follow NatSpec guidelines

### ISSUE THREAD

**Issue by rrtoledo** [clearmatics/zeth#192]
Let's follow [NatSpec](https://solidity.readthedocs.io/en/v0.6.4/natspec-format.html) for "documentation comments"

**Comment by AntoineRondelet** [comment]
Thread: https://github.com/clearmatics/zeth/pull/157#discussion_r402803686

**Comment by AntoineRondelet** [comment]
Contained in https://github.com/clearmatics/zeth/issues/321

**Comment by AntoineRondelet** [comment]
The existing smart-contracts have been updated to follow NatSpec. Closing this issue as a consequence.
