### ISSUE TITLE
Docker autobuild is constently failing

### ISSUE THREAD

**Issue by AntoineRondelet** [clearmatics/zeth#258]
For some reason the docker autobuild of the Dockerfile-base on `develop` has been constantly failing.
I looked at the logs on DockerHub but cannot really pin point what needs to be done to solve the issue and make `clearmatics/zeth-base` build correctly.
Building the image locally via `docker build --no-cache -f Dockerfile-base -t clearmatics/zeth-base .` works well (I passed the `--no-cache` flag to be sure that all steps were ran from scratch and catch any potential issue with the image).

Could I receive some assistance on this one?
Any help would be appreciated @eastata @Klazomenai :)

**Comment by eastata** [comment]
https://hub.docker.com/repository/registry-1.docker.io/clearmatics/zeth-base/builds/5525d7a3-8319-4fa6-a713-78b11fa4a8c2
```
virtual memory exhausted: Out of memory
```

**Comment by AntoineRondelet** [comment]
Thanks @eastata

**Comment by Klazomenai** [comment]
@eastata Is this issue a sub-task of #278 which will be covered within that issue and can be closed?

**Comment by eastata** [comment]
Should be resolved bt PR https://github.com/clearmatics/zeth/pull/313
