### ISSUE TITLE
Handling of custom ganache-cli package

### ISSUE THREAD

**Issue by dtebbs** [clearmatics/zeth#285]
#280 uses a custom version of the ganache-cli npm package which exposees some extrac precompiled contracts (for BLS12-377 and BW6-761 operations).
If possible, it would be nice to use npm rather than the submodule approach used for now.

Some notes:
- Depenencies take the form `ganache-cli` -> `ganache-core` -> `ethereumjs-vm` -> `libff.js` 
- ganache-cli uses a build step to compact all JS code into a single file, hence injecting custom npm packages into the hierarchy tree does not work (the *built* package is downloaded from npm without referencing any of the dependencies above, which are listed as `devDependenies`)
- referencing a github repo with a custom version of `ganache-cli` (clearmatics/ganache-cli) does not work, since `npm install` does not perform the above build, and `devDependencies` are not kept by the install process
- there is an indication that a `prepare` script can cause the devDependencies to be installed, but a quick test of this did not work (i.e. `zeth_contracts` references a custom `ganache-cli` github repo, with a `prepare` script that runs `npm run build`). Some variation of this approach seems possible, with more investigation.

**Comment by AntoineRondelet** [comment]
As discussed in https://github.com/clearmatics/zeth/pull/280#discussion_r494899796, another alternative may be to use a docker image to fetch and run our custom "experimental" ganache cli.

**Comment by AntoineRondelet** [comment]
Our custom ganache-cli is now packaged in a docker container that can be pulled via `docker pull ghcr.io/clearmatics/ganache-cli:latest` to "bypass" the use of the submodules if needed.
I think, serving ganache via a docker container is enough at this stage, and serves us well enough, hence I think this ticket can now be closed. @dtebbs what do you think?

**Comment by dtebbs** [comment]
Yes.  This seems to be resolved.  Closing.
