### ISSUE TITLE
Switch to Groth16

### ISSUE THREAD

**Issue by AntoineRondelet** [clearmatics/zeth#3]
Write a solidity verifier and switch the zksnark for the proof generation.

Reference paper: https://eprint.iacr.org/2016/260
See: https://github.com/scipr-lab/libsnark/blob/master/libsnark/zk_proof_systems/ppzksnark/r1cs_gg_ppzksnark/r1cs_gg_ppzksnark.hpp

**Comment by riemann89** [comment]
Added support in #22
