### ISSUE TITLE
Investigate caching for github actions

### ISSUE THREAD

**Issue by dtebbs** [clearmatics/zeth#324]
The barrier to running all tests (including those involving on-chain operations) is the time taken to build / install dependencies.  #150 

Docker may be one solution to this, but this presents issues when the content of the container must change. (To check the CI tests, one needs to invoke the CI to build the containers. Depending on versioning policies, this may affect the build of other branches, which breaks isolation.)

Investigate this as a solution for actions:
  https://docs.github.com/en/free-pro-team@latest/actions/guides/caching-dependencies-to-speed-up-workflows

(Good first steps would be the solidity compiler on macos, grpc on linux, etc)

**Comment by eastata** [comment]
GitHub will remove any cache entries that have not been accessed in over **7 days**.
There is no limit on the number of caches you can store, but the total size of all caches in a repository is limited to **5 GB**.

**Comment by dtebbs** [comment]
I see a few uses for this:

- cache the submodule dependencies to improve the current build times (worth measuring again, but I think libsodium, libff, etc take up a significant proportion of the build time)
- cache other dependencies addressing issues that make it difficult to just build all components and run integration tests:
  - grpc on linux
  - solidity compiler on mac
  - ... probably others
 
Integration tests in CI is a big goal.
Note, if we get the solidity compiler cached on mac, (for example), we could run integration tests at least on this platform.  A massive improvement over the current situation.

**Comment by dtebbs** [comment]
For background:  the solidity compiler is installed when setting up the `client` python project (by invoking the `py-solc-x`) package.  It gets written to `~/.solcx/solc-vXXXX`.  On mac, there is no binary so a huge build gets invoked.

**Comment by dtebbs** [comment]
> GitHub will remove any cache entries that have not been accessed in over 7 days.

This is good to know, @eastata .
I guess we may want something like a nightly build on `develop` to ensure we always have a reasonable set of dependencies cached.

**Comment by AntoineRondelet** [comment]
This ticket aims to be addressed in #326

**Comment by AntoineRondelet** [comment]
This ticket aims to be partially addressed in #326 which proposes modified workflows in which dependencies are cached to be used across jobs and fasten their execution time.

In the meantime, @eastata is looking into caching docker builds on GA, as well as migrating to ghcr.

**Comment by AntoineRondelet** [comment]
Closing this issue now that #326 is merged.
