### ISSUE TITLE
Consider updating exponents and round values for MiMC

### ISSUE THREAD

**Issue by dtebbs** [clearmatics/zeth#364]
Now that we have confirmation about exponents of the form $2^t+1$ in prime fields, we could potentially reduce the number of constraints in the joinsplit circuit.
- [x] Small update to specs to mention the values specified there
- [x] Update zeth circuits, contract code and python
- [ ] Update values for BW6-761 and MNT{4,6} in Zecale

**Comment by AntoineRondelet** [comment]
See #369

**Comment by AntoineRondelet** [comment]
@dtebbs could you update this ticket, now that #369 is merged?

**Comment by dtebbs** [comment]
Closing this issue for now.  Remaining curves will be handled in clearmatics/zecale#81.
