### ISSUE TITLE
Debug build triggers asserts

### ISSUE THREAD

**Issue by dtebbs** [clearmatics/zeth#37]
When running tests or constructing the joinsplit circuit, asserts are hit in 3rd party libs and internal code:
```
$ cmake -DCMAKE_BUILD_TYPE=Debug .. && make check
```

Initially, libsnark asserts due to empty annotations.  If those asserts are disabled, zeth circuit gen asserts related to number of inputs.

**Comment by AntoineRondelet** [comment]
Thanks a lot for that @dtebbs, just merged your PR
