### ISSUE TITLE
Dependencies in cmake files

### ISSUE THREAD

**Issue by dtebbs** [clearmatics/zeth#46]
Source file and dependency specifications seem to suffer from a few problems:
- source files are re-specified for every executable (utility and unit test) which inflates build times
- some include files and .tcc files are not specified as belonging to any target which means that incremental builds (using Makefiles) are often incomplete.

**Comment by AntoineRondelet** [comment]
Closed as the corresponding PR has been merged.
Thanks for that @dtebbs
