### ISSUE TITLE
Gas optimization (general): Initializing to null values

### ISSUE THREAD

**Issue by klmcdon** [clearmatics/zeth#71]
On multiple occasions (in multiple contracts), variables are explicitly initialized to their null values. This is unnecessary as initialization to null values is the default and explicitly initializing to null values costs additional gas. 

For example, loops in MerkleTreeSha256 are currently written as "uint i=0;" but using "uint i;" would achieve the same outcome and reduce the gas costs for deployment and execution.

**Comment by rrtoledo** [comment]
Done in fix-todo.
