### ISSUE TITLE
Optimize zeth contracts

### ISSUE THREAD

**Issue by AntoineRondelet** [clearmatics/zeth#94]
Let's do a pass on the smart contracts to try and optimize them in order to reduce the gas cost of the state transitions

**Comment by AntoineRondelet** [comment]
Related issues: #71 #72

**Comment by rrtoledo** [comment]
I already started fixing these in the fix-todo branch

**Comment by AntoineRondelet** [comment]
Closing this issue as it consisted in doing a first pass on the smart contract to optimize the gas consumption of their execution. This has been done as part of #138 which has been merged. Further optimizations can be reported in new tickets, and addressed in new PRs.
